version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 396503876336.dkr.ecr.us-east-1.amazonaws.com/production-drupal
  build:
    commands:
      - echo "Build phase"
  post_build:
    commands:
      - echo "Post build phase"

artifacts:
  files:
    - imageDefinitions.json
    - appspec.yml
    - taskdef.json
