version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - IMAGE_TAG=$IMAGE_TAG
      - echo "Getting latest task definition..."
      - aws ecs describe-task-definition --task-definition production-drupal-app --region $AWS_DEFAULT_REGION --query 'taskDefinition.taskDefinitionArn' --output text > taskdef_arn.txt
      - TASKDEF_ARN=$(cat taskdef_arn.txt)
      - echo "Task Definition ARN: $TASKDEF_ARN"
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:latest ./docker
  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDefinitions.json
      - echo "Creating appspec.yml..."
      - echo "version: 0.0" > appspec.yml
      - echo "Resources:" >> appspec.yml
      - echo "  - TargetService:" >> appspec.yml
      - echo "      Type: AWS::ECS::Service" >> appspec.yml
      - echo "      Properties:" >> appspec.yml
      - echo "        TaskDefinition: $TASKDEF_ARN" >> appspec.yml
      - echo "        LoadBalancerInfo:" >> appspec.yml
      - echo "          ContainerName: drupal-app" >> appspec.yml
      - echo "          ContainerPort: 80" >> appspec.yml
      - echo "Creating custom taskdef.json without MariaDB EFS volume..."
      - echo "{" > taskdef.json
      - echo '  "executionRoleArn": "arn:aws:iam::396503876336:role/production-ecs-execution-role",' >> taskdef.json
      - echo '  "containerDefinitions": [' >> taskdef.json
      - echo '    {' >> taskdef.json
      - echo '      "name": "drupal-mariadb",' >> taskdef.json
      - echo '      "image": "mariadb:10.6",' >> taskdef.json
      - echo '      "portMappings": [' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "containerPort": 3306,' >> taskdef.json
      - echo '          "protocol": "tcp"' >> taskdef.json
      - echo '        }' >> taskdef.json
      - echo '      ],' >> taskdef.json
      - echo '      "environment": [' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "name": "MYSQL_ROOT_PASSWORD",' >> taskdef.json
      - echo '          "value": "drupal_root_password"' >> taskdef.json
      - echo '        },' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "name": "MYSQL_DATABASE",' >> taskdef.json
      - echo '          "value": "drupal"' >> taskdef.json
      - echo '        },' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "name": "MYSQL_USER",' >> taskdef.json
      - echo '          "value": "drupal_user"' >> taskdef.json
      - echo '        },' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "name": "MYSQL_PASSWORD",' >> taskdef.json
      - echo '          "value": "drupal_password"' >> taskdef.json
      - echo '        }' >> taskdef.json
      - echo '      ],' >> taskdef.json
      - echo '      "mountPoints": [],' >> taskdef.json
      - echo '      "logConfiguration": {' >> taskdef.json
      - echo '        "logDriver": "awslogs",' >> taskdef.json
      - echo '        "options": {' >> taskdef.json
      - echo '          "awslogs-group": "/ecs/production-drupal-mariadb",' >> taskdef.json
      - echo '          "awslogs-region": "us-east-1",' >> taskdef.json
      - echo '          "awslogs-stream-prefix": "ecs"' >> taskdef.json
      - echo '        }' >> taskdef.json
      - echo '      },' >> taskdef.json
      - echo '      "healthCheck": {' >> taskdef.json
      - echo '        "command": ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pdrupal_root_password || exit 1"],' >> taskdef.json
      - echo '        "interval": 30,' >> taskdef.json
      - echo '        "timeout": 5,' >> taskdef.json
      - echo '        "retries": 3,' >> taskdef.json
      - echo '        "startPeriod": 60' >> taskdef.json
      - echo '      }' >> taskdef.json
      - echo '    },' >> taskdef.json
      - echo '    {' >> taskdef.json
      - echo '      "name": "drupal-app",' >> taskdef.json
      - echo "      \"image\": \"$REPOSITORY_URI:$IMAGE_TAG\"," >> taskdef.json
      - echo '      "portMappings": [' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "containerPort": 80,' >> taskdef.json
      - echo '          "protocol": "tcp"' >> taskdef.json
      - echo '        }' >> taskdef.json
      - echo '      ],' >> taskdef.json
      - echo '      "environment": [' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "name": "DB_HOST",' >> taskdef.json
      - echo '          "value": "localhost"' >> taskdef.json
      - echo '        },' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "name": "DB_NAME",' >> taskdef.json
      - echo '          "value": "drupal"' >> taskdef.json
      - echo '        },' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "name": "DB_USER",' >> taskdef.json
      - echo '          "value": "drupal_user"' >> taskdef.json
      - echo '        },' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "name": "DB_PASS",' >> taskdef.json
      - echo '          "value": "drupal_password"' >> taskdef.json
      - echo '        }' >> taskdef.json
      - echo '      ],' >> taskdef.json
      - echo '      "mountPoints": [' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "sourceVolume": "drupal-content",' >> taskdef.json
      - echo '          "containerPath": "/var/www/html/web/sites/default/files",' >> taskdef.json
      - echo '          "readOnly": false' >> taskdef.json
      - echo '        }' >> taskdef.json
      - echo '      ],' >> taskdef.json
      - echo '      "logConfiguration": {' >> taskdef.json
      - echo '        "logDriver": "awslogs",' >> taskdef.json
      - echo '        "options": {' >> taskdef.json
      - echo '          "awslogs-group": "/ecs/production-drupal-app",' >> taskdef.json
      - echo '          "awslogs-region": "us-east-1",' >> taskdef.json
      - echo '          "awslogs-stream-prefix": "ecs"' >> taskdef.json
      - echo '        }' >> taskdef.json
      - echo '      },' >> taskdef.json
      - echo '      "healthCheck": {' >> taskdef.json
      - echo '        "command": ["CMD-SHELL", "curl -f http://localhost/ || exit 1"],' >> taskdef.json
      - echo '        "interval": 30,' >> taskdef.json
      - echo '        "timeout": 5,' >> taskdef.json
      - echo '        "retries": 3,' >> taskdef.json
      - echo '        "startPeriod": 60' >> taskdef.json
      - echo '      },' >> taskdef.json
      - echo '      "dependsOn": [' >> taskdef.json
      - echo '        {' >> taskdef.json
      - echo '          "containerName": "drupal-mariadb",' >> taskdef.json
      - echo '          "condition": "HEALTHY"' >> taskdef.json
      - echo '        }' >> taskdef.json
      - echo '      ]' >> taskdef.json
      - echo '    }' >> taskdef.json
      - echo '  ],' >> taskdef.json
      - echo '  "volumes": [' >> taskdef.json
      - echo '    {' >> taskdef.json
      - echo '      "name": "drupal-content",' >> taskdef.json
      - echo '      "efsVolumeConfiguration": {' >> taskdef.json
      - echo '        "fileSystemId": "fs-005b8956cdec1dbd1",' >> taskdef.json
      - echo '        "rootDirectory": "/",' >> taskdef.json
      - echo '        "transitEncryption": "ENABLED",' >> taskdef.json
      - echo '        "transitEncryptionPort": 2049,' >> taskdef.json
      - echo '        "authorizationConfig": {' >> taskdef.json
      - echo '          "accessPointId": "fsap-026083cc1683ec80d",' >> taskdef.json
      - echo '          "iam": "ENABLED"' >> taskdef.json
      - echo '        }' >> taskdef.json
      - echo '      }' >> taskdef.json
      - echo '    }' >> taskdef.json
      - echo '  ],' >> taskdef.json
      - echo '  "family": "production-drupal-app",' >> taskdef.json
      - echo '  "networkMode": "awsvpc",' >> taskdef.json
      - echo '  "requiresCompatibilities": ["FARGATE"],' >> taskdef.json
      - echo '  "cpu": 1024,' >> taskdef.json
      - echo '  "memory": 2048,' >> taskdef.json
      - echo '  "taskRoleArn": "arn:aws:iam::396503876336:role/production-ecs-task-role"' >> taskdef.json
      - echo "}" >> taskdef.json
      - echo "Uploading artifacts to S3..."
      - aws s3 cp appspec.yml s3://production-drupal-codebuild-artifacts-lwouy9p2/production-drupal-docker-build/appspec.yml
      - aws s3 cp taskdef.json s3://production-drupal-codebuild-artifacts-lwouy9p2/production-drupal-docker-build/taskdef.json
      - aws s3 cp imageDefinitions.json s3://production-drupal-codebuild-artifacts-lwouy9p2/production-drupal-docker-build/imageDefinitions.json

artifacts:
  files:
    - imageDefinitions.json
    - appspec.yml
    - taskdef.json
  discard-paths: no