name: Build Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      run: |
        docker build --platform linux/amd64 -t ${{ steps.login-ecr.outputs.registry }}/production-drupal:${{ github.sha }} -f docker/Dockerfile .
        docker tag ${{ steps.login-ecr.outputs.registry }}/production-drupal:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/production-drupal:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/production-drupal:${{ github.sha }}
        docker push ${{ steps.login-ecr.outputs.registry }}/production-drupal:latest

    - name: Create deployment file
      run: |
        echo '{"ImageURI":"${{ steps.login-ecr.outputs.registry }}/production-drupal:${{ github.sha }}"}' > imageDefinitions.json

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-files
        path: imageDefinitions.json